default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: 123777mp
  host: localhost
  port: 5433

development:
  <<: *default
  database: bayes_development

test:
  <<: *default
  database: bayes_test